import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

const translations = {
  en: {
    brand: "Iordanou Residences",
    tagline: "Traditional holiday homes on the island of Lesvos",
    home: "Home",
    explore: "Explore Lesvos",
    dashboard: "Host Dashboard",
    bookDirectly: "Book Directly",
    sleepsUpTo: "Sleeps up to",
    guests: "guests",
    perNight: "/ night",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    amenities: "Amenities",
    checkIn: "Check-in",
    checkOut: "Check-out",
    selectDates: "Select your dates",
    nights: "nights",
    night: "night",
    subtotal: "Subtotal",
    weeklyDiscount: "Weekly stay discount (10%)",
    couponDiscount: "Coupon discount",
    total: "Total",
    applyCoupon: "Promo Code",
    couponPlaceholder: "Enter promo code",
    apply: "Apply",
    minStay: "Minimum stay: 2 nights",
    bookNow: "Request via WhatsApp",
    guestDetails: "Guest Details",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone",
    numGuests: "Number of Guests",
    specialRequests: "Special Requests (optional)",
    priceSummary: "Price Summary",
    confirmBooking: "Send WhatsApp Request",
    whatsappCTA: "Request Booking via WhatsApp",
    whatsappMsg: "Hello! I would like to request a direct booking at Iordanou Residences for {property}. Dates: {checkIn} to {checkOut} ({nights} nights). Promo Code used: {coupon}. Total Estimated Price: €{total}.",
    bookingSuccess: "Booking Request Sent!",
    bookingSuccessMsg: "Your WhatsApp booking request has been sent. We will confirm shortly.",
    bookingRef: "Booking Reference",
    backHome: "Back to Home",
    ourResidences: "Our Residences",
    landmarks: "Local Landmarks",
    hiddenLocations: "Beaches & Places",
    allCategories: "All",
    exploreTitle: "Explore Lesvos",
    exploreSubtitle: "Discover the hidden gems and timeless beauty of our island",
    mapView: "Map View",
    gridView: "Grid View",
    reservations: "Reservations",
    revenue: "Revenue",
    coupons: "Coupons",
    guideManager: "Guide Manager",
    mapManager: "Map Points",
    totalRevenue: "Total Revenue",
    totalBookings: "Total Bookings",
    confirmedBookings: "Confirmed",
    pendingBookings: "Pending",
    cancelledBookings: "Cancelled",
    createCoupon: "Create Coupon",
    addGuideEntry: "Add Guide Entry",
    addMapPoint: "Add Map Point",
    status: "Status",
    property: "Property",
    guest: "Guest",
    dates: "Dates",
    amount: "Amount",
    source: "Source",
    actions: "Actions",
    confirm: "Confirm",
    cancel: "Cancel",
    active: "Active",
    inactive: "Inactive",
    revoke: "Revoke",
    activate: "Activate",
    code: "Code",
    discount: "Discount",
    uses: "Uses",
    title: "Title",
    description: "Description",
    category: "Category",
    image: "Image URL",
    latitude: "Latitude",
    longitude: "Longitude",
    save: "Save",
    delete: "Delete",
    edit: "Edit",
    close: "Close",
    unavailable: "Unavailable",
    pricePerNight: "Price per night",
    weeklyDiscountNote: "10% off for stays of 7+ nights",
    viewProperty: "View Property",
    viewAndBook: "View Property & Book",
    properties: "Properties",
    calendarSync: "Calendar Sync",
    icalUrl: "iCal URL",
    syncCalendar: "Sync Calendar",
    blockedDates: "Blocked Dates",
    residence: "Residence",
    landmark: "Landmark",
    location: "Location",
    beach: "Beach",
    heroTitle: "Your Greek Island Escape",
    heroSubtitle: "Two hand-picked traditional homes, nestled in the heart of Lesvos",
    whyBook: "Why Book Direct?",
    reason1Title: "Best Price Guaranteed",
    reason1Desc: "No middleman fees. The price you see is the best available.",
    reason2Title: "Flexible Cancellation",
    reason2Desc: "Plans change — we understand. Cancel up to 7 days before for a full refund.",
    reason3Title: "Local Host Support",
    reason3Desc: "Direct line to your host for personalized tips and assistance.",
    exploreLesvos: "Explore Lesvos",
    discoverMore: "Discover More",
    addManualBooking: "Add Manual Booking",
    bookingSource: "Booking Source",
    noResults: "No entries found",
    ourProperties: "Our Residences",
    beaches: "Beaches",
  },
  el: {
    brand: "Ιορδάνου Residences",
    tagline: "Παραδοσιακά σπίτια διακοπών στο νησί της Λέσβου",
    home: "Αρχική",
    explore: "Εξερεύνησε τη Λέσβο",
    dashboard: "Πίνακας Ελέγχου",
    bookDirectly: "Κράτηση Απευθείας",
    sleepsUpTo: "Χωρητικότητα έως",
    guests: "επισκέπτες",
    perNight: "/ βράδυ",
    bedrooms: "Υπνοδωμάτια",
    bathrooms: "Μπάνια",
    amenities: "Παροχές",
    checkIn: "Άφιξη",
    checkOut: "Αναχώρηση",
    selectDates: "Επιλέξτε ημερομηνίες",
    nights: "βράδια",
    night: "βράδυ",
    subtotal: "Μερικό σύνολο",
    weeklyDiscount: "Έκπτωση εβδομαδιαίας διαμονής (10%)",
    couponDiscount: "Έκπτωση κουπονιού",
    total: "Σύνολο",
    applyCoupon: "Κωδικός Προσφοράς",
    couponPlaceholder: "Εισάγετε κωδικό προσφοράς",
    apply: "Εφαρμογή",
    minStay: "Ελάχιστη διαμονή: 2 βράδια",
    bookNow: "Αίτηση μέσω WhatsApp",
    guestDetails: "Στοιχεία Επισκέπτη",
    fullName: "Ονοματεπώνυμο",
    email: "Email",
    phone: "Τηλέφωνο",
    numGuests: "Αριθμός Επισκεπτών",
    specialRequests: "Ειδικά Αιτήματα (προαιρετικά)",
    priceSummary: "Σύνοψη Τιμής",
    confirmBooking: "Αποστολή μέσω WhatsApp",
    whatsappCTA: "Αίτηση Κράτησης μέσω WhatsApp",
    whatsappMsg: "Γεια σας! Θα ήθελα να κάνω απευθείας κράτηση στα Ιορδάνου Residences για {property}. Ημερομηνίες: {checkIn} έως {checkOut} ({nights} βράδια). Κωδικός Προσφοράς: {coupon}. Εκτιμώμενο Σύνολο: €{total}.",
    bookingSuccess: "Το Αίτημα Εστάλη!",
    bookingSuccessMsg: "Το αίτημα κράτησης σας μέσω WhatsApp στάλθηκε. Θα επιβεβαιώσουμε σύντομα.",
    bookingRef: "Κωδικός Κράτησης",
    backHome: "Επιστροφή στην Αρχική",
    ourResidences: "Τα Σπίτια μας",
    landmarks: "Τοπικά Αξιοθέατα",
    hiddenLocations: "Παραλίες & Τοποθεσίες",
    allCategories: "Όλα",
    exploreTitle: "Εξερεύνησε τη Λέσβο",
    exploreSubtitle: "Ανακαλύψτε τα κρυφά διαμάντια και την αιώνια ομορφιά του νησιού μας",
    mapView: "Χάρτης",
    gridView: "Πλέγμα",
    reservations: "Κρατήσεις",
    revenue: "Έσοδα",
    coupons: "Κουπόνια",
    guideManager: "Διαχείριση Οδηγού",
    mapManager: "Σημεία Χάρτη",
    totalRevenue: "Συνολικά Έσοδα",
    totalBookings: "Συνολικές Κρατήσεις",
    confirmedBookings: "Επιβεβαιωμένες",
    pendingBookings: "Εκκρεμείς",
    cancelledBookings: "Ακυρωμένες",
    createCoupon: "Δημιουργία Κουπονιού",
    addGuideEntry: "Προσθήκη Εγγραφής",
    addMapPoint: "Προσθήκη Σημείου",
    status: "Κατάσταση",
    property: "Κατάλυμα",
    guest: "Επισκέπτης",
    dates: "Ημερομηνίες",
    amount: "Ποσό",
    source: "Πηγή",
    actions: "Ενέργειες",
    confirm: "Επιβεβαίωση",
    cancel: "Ακύρωση",
    active: "Ενεργό",
    inactive: "Ανενεργό",
    revoke: "Απενεργοποίηση",
    activate: "Ενεργοποίηση",
    code: "Κωδικός",
    discount: "Έκπτωση",
    uses: "Χρήσεις",
    title: "Τίτλος",
    description: "Περιγραφή",
    category: "Κατηγορία",
    image: "URL Εικόνας",
    latitude: "Γεωγρ. Πλάτος",
    longitude: "Γεωγρ. Μήκος",
    save: "Αποθήκευση",
    delete: "Διαγραφή",
    edit: "Επεξεργασία",
    close: "Κλείσιμο",
    unavailable: "Μη διαθέσιμο",
    pricePerNight: "Τιμή ανά βράδυ",
    weeklyDiscountNote: "10% έκπτωση για διαμονή 7+ βράδια",
    viewProperty: "Δείτε το Κατάλυμα",
    viewAndBook: "Δείτε & Κράτηση",
    properties: "Καταλύματα",
    calendarSync: "Συγχρονισμός Ημερολογίου",
    icalUrl: "iCal URL",
    syncCalendar: "Συγχρονισμός",
    blockedDates: "Αποκλεισμένες Ημερομηνίες",
    residence: "Κατάλυμα",
    landmark: "Αξιοθέατο",
    location: "Τοποθεσία",
    beach: "Παραλία",
    heroTitle: "Η Ελληνική σας Απόδραση",
    heroSubtitle: "Δύο επιλεγμένα παραδοσιακά σπίτια, στην καρδιά της Λέσβου",
    whyBook: "Γιατί Απευθείας Κράτηση;",
    reason1Title: "Εγγύηση Καλύτερης Τιμής",
    reason1Desc: "Χωρίς μεσάζοντες. Η τιμή που βλέπετε είναι η καλύτερη διαθέσιμη.",
    reason2Title: "Ευέλικτη Ακύρωση",
    reason2Desc: "Τα σχέδια αλλάζουν — το καταλαβαίνουμε. Ακυρώστε έως 7 μέρες πριν.",
    reason3Title: "Τοπική Υποστήριξη",
    reason3Desc: "Απευθείας επικοινωνία με τον οικοδεσπότη σας.",
    exploreLesvos: "Εξερεύνησε τη Λέσβο",
    discoverMore: "Μάθε Περισσότερα",
    addManualBooking: "Χειροκίνητη Κράτηση",
    bookingSource: "Πηγή Κράτησης",
    noResults: "Δεν βρέθηκαν εγγραφές",
    ourProperties: "Τα Καταλύματά μας",
    beaches: "Παραλίες",
  }
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('iordanou_lang') || 'en');

  const handleSetLang = (newLang) => {
    setLang(newLang);
    localStorage.setItem('iordanou_lang', newLang);
  };

  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const localField = (obj, field) => {
    if (!obj) return '';
    return obj[`${field}_${lang}`] || obj[`${field}_en`] || '';
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: handleSetLang, t, localField }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
}
